# Generated by Django 5.0.1 on 2024-02-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
