# Generated by Django 5.0.1 on 2024-01-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='user',
            new_name='user_comment',
        ),
    ]
