# Generated by Django 5.0.1 on 2024-02-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0002_commentaccommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
