# Generated by Django 5.0.1 on 2024-02-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0002_rename_image_imageaccommodation_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
