# Generated by Django 5.0.1 on 2024-02-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0002_alter_commentpost_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='user',
        ),
    ]
