# Generated by Django 5.0.1 on 2024-02-19 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0003_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='accommodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_image', to='RentApp.accommodation'),
        ),
    ]
