# Generated by Django 5.0.1 on 2024-02-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0003_accommodation_description_user_last_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
